spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multpart:
      max-file-size: 50MB
      max-request-size: 50MB

# Production (down)
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5433/db